### ISSUE TITLE
Consider adding husky and lint-staged for precommit tasks

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#114]
In the spirit of keeping code maintainable, pre-commit tasks are a blessing. Consider adding [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) for managing pre-commit tasks.

Examples of pre-commit tasks can include running tests, linting and formatting. For a real world example of this in action, see https://github.com/forem/forem/blob/master/package.json#L28-L71 .

Here is an example where linting fails as well as tests for some changes that were made to a component.

```bash
husky > pre-commit (node v12.18.3)
  ✖ eslint --fix [FAILED]
    ◼ jest --findRelatedTests
  ↓ No staged files match {app,spec,config,lib}/**/*.rb [SKIPPED]
  ↓ No staged files match app/views/**/*.jbuilder [SKIPPED]
  ↓ No staged files match Gemfile [SKIPPED]
  ↓ No staged files match app/**/*.html.erb [SKIPPED]
  ↓ No staged files match *.json [SKIPPED]
  ↓ No staged files match *.scss [SKIPPED]
  ↓ No staged files match *.md [SKIPPED]
  ↓ No staged files match *.svg [SKIPPED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ eslint --fix:

/Users/nickytonline/dev/dev.to/app/javascript/crayons/Button/Button.jsx
  65:9  error  'ComponentName' is assigned a value but never used  no-unused-vars
  66:9  error  'Icon' is assigned a value but never used           no-unused-vars

✖ 2 problems (2 errors, 0 warnings)

husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by jhuynh85** [comment]
I can take a stab at this

**Comment by jhuynh85** [comment]
I have the following precommit tasks so far:

```
"lint-staged": {
    "*.{js,jsx}": [
      "prettier --write",
      "eslint --fix"
    ],
    "*.json": [
      "prettier --write"
    ]
  }
```

Is there anything else you feel we should add?

**Comment by nickytonline** [comment]
@jhuynh85, I've just assigned this to you.

You can also add Markdown files as well as CSS file for prettier to format. That work for you @drewclem and @pickleat? At some point, we could also look into incorporating [stylelint](https://github.com/stylelint/stylelint) into the project, but baby steps. 😄

**Comment by drewclem** [comment]
That sounds good to me

**Comment by nickytonline** [comment]
@drewclem @sethburtonhall, looks like this work got removed when we moved to NEXT.js.
