### ISSUE TITLE
Generate list of contributors at build time

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#116]
Currently Contributors.js hits the GitHub API to retrieve the list of contributors to this repository and then makes *n* (number of contributors) calls again to the GitHub API to retrieve additional information about contributors.

Consider building the list of contributors at build time since this list only ever changes when new commits are pushed to the main branch.

It will make the Contributors page load super quick, https://protege.dev/contributors and avoid errors when the GitHub API has been it too much.

It would also remove the need for #94 since there would no longer be a loading phase for the Contributors page.

**Comment by drewclem** [comment]
resolved with https://github.com/drewclem/protege/pull/115
