### ISSUE TITLE
Accessibility Issues

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#118]
Accessibility Issues

In the PostAJobForm.js file, the `htmlFor` JSX prop (rendered as [for](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attr-for) HTML attribute) should be `position-type` not `positionType` .

![image](https://user-images.githubusercontent.com/833231/90591592-782e9080-e1b1-11ea-86e0-3e2ef1478726.png)

![image](https://user-images.githubusercontent.com/833231/90591600-8086cb80-e1b1-11ea-9066-b6ee0aea31c5.png)

The `.text-blue-500` CSS class’ `color` property does not provide enough contrast. I messed around with the [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/) tool and this seemed like a suitable colour, `#55556D`. that provides enough contrast and it still looks good.

![image](https://user-images.githubusercontent.com/833231/90592606-fa1fb900-e1b3-11ea-83e1-688efb6e9aa7.png)

The validation error `.input-error` CSS class’ `color` property does not provide enough contrast. I messed around with the [WebAIM Contrast Checker](https://webaim.org/resources/contrastchecker/) tool and this seemed like a suitable colour, `#AF1818`. that provides enough contrast and it still looks good.

The `<ReactQuill />` component has several accessibility issues. See https://github.com/quilljs/quill/issues/2038 . It would probably make for a great PR that would help all using this editor support better accessibility.

**Comment by nickytonline** [comment]
Note that are still other accessibility issues in the site. Take the Axe browser extension ([Chrome](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd) | [Firefox](https://addons.mozilla.org/en-CA/firefox/addon/axe-devtools/)) for a spin to find more future contributors!

**Comment by drewclem** [comment]
@nickytonline Thanks for this issue! I'll definitely comb through with Axe to find our other issues and get them up

**Comment by nickytonline** [comment]
There is also the WebAIM [WAVE browser extension](https://wave.webaim.org/extension).

**Comment by drewclem** [comment]
Resolved with https://github.com/drewclem/protege/pull/121
