### ISSUE TITLE
Consider adding a GitHub PR template

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#120]
The title says it all. 😎 Consider adding a GitHub PR template. If you are looking for inspiration, see Forem's [PR template](https://github.com/forem/forem/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by pickleat** [comment]
Closing this as it was resolved by @muchirijane and @drewclem happy to open back up if I misunderstood.

**Comment by muchirijane** [comment]
Hey, @pickleat would you kindly open this issue back I found a solution for it.
