### ISSUE TITLE
Error: 'bin' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by jhuynh85** [drewclem/protege#127]
**STEPS TO REPRODUCE**
1. On a Windows machine, run `npm start`

**RESULT**
`npm start` will fail with the error `'bin' is not recognized as an internal or external command,
operable program or batch file.`

**ADDITIONAL INFO**
This error is due to `npm start` also running the `get-contributors` script which is the command `bin/generate-contributors-json.js`. This is not recognized as a valid command in Windows.

**SOLUTION 1**
Change the `get-contributors` script from `bin/generate-contributors-json.js` to `node bin/generate-contributors-json.js`

**SOLUTION 2**
Install the [cross-env](https://www.npmjs.com/package/cross-env) package which will allow the same npm scripts to be run on all platforms. This also has the benefit of avoiding potential issues with setting environment variables directly in npm scripts (which requires different syntax in Windows).

**Comment by jhuynh85** [comment]
Let me know if you guys want to fix this and which solution you prefer

**Comment by nickytonline** [comment]
This is no longer an issue at all since #228.
