### ISSUE TITLE
Consider renaming master to main

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#130]
Consider renaming master to main.

@sw-yx has a nice [cheat sheet](https://dev.to/swyx/move-primary-git-branch-from-master-to-main-m7c) for this.

**Comment by muchirijane** [comment]
Hey, Let me try working on this issue 👍🏽

**Comment by muchirijane** [comment]
Quick question, should I use feature/main branch or just main as a branch.

**Comment by drewclem** [comment]
That's a good question that I don't have the answer to. @pickleat or @nickytonline Any ideas on how to handle this?

**Comment by pickleat** [comment]
I think it needs to be the base branch so just `main` @drewclem you'll need to update the netlify configs once it's fixed up! And then we'll delete the old branching. We also need to make sure `develop` is based off the up to date version of the branch.

**Comment by nickytonline** [comment]
This is a task that a contributor cannot do. It will have to be maintainer of the project. This change cannot be completed via a PR.

- As @pickleat mentioned, once the branch has been renamed, ensure that the Netlify build is pointing to the `main` branch.
- In regards to the `develop` branch, nothing will need to be done as long as it is up to date before renaming `master`. Once the change has been made, use gitflow as usual, but with `develop`/`main`.
- Also, in the GitHub UI, set the default branch to the new branch.

**Comment by pickleat** [comment]
Thanks for the clarification @nickytonline, looks like this one is on you @drewclem.

**Comment by muchirijane** [comment]
I totally understand. 💯

**Comment by drewclem** [comment]
Done!
