### ISSUE TITLE
Update Tailwind to Newest version and incorporate PurgeCSS into our build / dev branches. 

### ISSUE THREAD

**Issue by pickleat** [drewclem/protege#144]
## Is your feature request related to a problem? Please describe.

It looks like we are shipping ALL of the generated css that Tailwind creates. This should only be true for _local_ development. 

## Describe the solution you'd like

Add a build task to run PurgeCSS to remove all unused CSS from the `main` and `develop` branches, since they are shipped to the browser.
- [Tailwind PurgeCSS Docs](https://tailwindcss.com/docs/controlling-file-size#basic-usage)
- I vote we use the manual version for now, because its not that often that css needs to be messed with for OS features, and can cause issues with the `watch` script that rebuilds the .css often leading to merge issues on branches with altered CSS. 
```js
// tailwind.config.js
module.exports = {
  purge: {
    enabled: true,
    content: ['./src/**/*.html'],
  },
  // ...
}
```
## Describe alternatives you've considered

- For my second suggestion we could just turn off the `watch script` from the `package.json` and it wouldn't rebuild the css automatically, but it could cause other issues when styling IS being updated. 

### Additional context

Open to discussion on this, but it's an idea I was thinking about as I currently deal with merge conflicts on another PR. 

## Steps to Complete

- [ ] Update TailwindCSS to newest version
- [ ] Incorporate PurgeCSS into Main/Develop branches

**Comment by drewclem** [comment]
@pickleat We currently don't have purgecss. Just postcss and tailwind doing their thing.

I like option 1. We're not doing anything extravagant with styling so it should be straight forward.

**Comment by pickleat** [comment]
Just realized why, purgecss is built in in tailwind ^1.4 so we should also bump up to the newest version as well. and include this.

**Comment by pickleat** [comment]
Changed the title to reflect that larger scope of this.

**Comment by pickleat** [comment]
Running PurgeCSS on this reduced our CSS by 70%!

**Comment by drewclem** [comment]
That's incredible! should this task be closed with our new pre-commit hooks in place? Or are there still items here that needs completing?

**Comment by pickleat** [comment]
I'm still working on it. There are still some weird config things and some other things that I'm trying to get any unnecessary code of out. I'll put in a PR.

**Comment by drewclem** [comment]
Ah ok. I misunderstood then. I had the recent pre-commit hooks PR mixed up with this one.
