### ISSUE TITLE
Put Drew and Andy at the bottom of the contributors list

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#145]
## Goal

This will place Andy and I at the bottom of the contributors list, under a Founders heading.

## Reason

The purpose of the contributors page is to highlight the amazing individuals who have contributed their time to improving this platform. There's no need to for us to be at the top of this list. Throw us at the bottom underneath a Founders heading. 

### Tips

There's a few places that need to be touched to make this happen.

- In ContributorsList in Contributors.js, add check on line 67 similar to ImgBotApp, accept use our github names to filter us out of the list
- Below <ContributorsList on line 55 in that same file add an h3 for Founders and then place our cards there

## Definition of Done

- [ ] Drew and Andy are filtered out of contributors list array
- [ ] A Founders heading is present below the list of contributors
- [ ] Contributor cards for Drew and Andy are present below Founders heading
- [ ] Image, social media links, number of commits, and github name are present

**Comment by AlbertoPdRF** [comment]
Hey! I've just found this project and thought about giving a go to this issue. However, I'd like to propose a slightly different approach as the one you outlined. How does filtering contributors first with:

```javascript
const filteredContributors = contributors.reduce(
  (allContributors, contributor) => {
    allContributors[
      ['drewclem', 'pickleat'].includes(contributor.login)
        ? 'founders'
        : 'regular'
    ].push(contributor)
    return allContributors
  },
  { founders: [], regular: [] }
)
```

and then changing line 67 to:

```javascript
<ContributorsList contributors={allContributors.regular} />

<h3>Founders</h3>
<ContributorsList contributors={allContributors.founders} />
```

sound? Also, which classes would you use for the `h3` element?

**Comment by pickleat** [comment]
In principle that solution makes sense to me! I'd say go for it. We can always tweak. 

For the `<h3>` I'd match the classes in the `<h1>` above: 
`<h1 className='text-2xl font-semibold text-blue-900 mb-3'>`

**Comment by drewclem** [comment]
@AlbertoPdRF That sounds great! As @pickleat said, use the H1 for reference - but text-2xl should probably become text-xl or text-lg.

**Comment by drewclem** [comment]
Closed with https://github.com/drewclem/protege/pull/156 Thanks @AlbertoPdRF
