### ISSUE TITLE
generate-contributors-json.js hits a rate limit if you restart the server often. 

### ISSUE THREAD

**Issue by pickleat** [drewclem/protege#153]
## Describe the bug

generate-contributors-json.js hits a rate limit if you restart the dev server often. 

## To Reproduce

Restart the dev server multiple times (like say to re-run PostCSS build), eventually you get an error from running the `generate-contributors-json.js` The error isn't clear at first. But adding 
`console.log(rawContributors)` to line 65 gets you this error

```
{
  message: "API rate limit exceeded for 104.8.63.136. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  documentation_url: 'https://developer.github.com/v3/#rate-limiting'
}
```

## Solution Options

1. It looks like we need to add an oath secret we can increase the rate limit.
2. We could stop the script running in development and only use it for production builds. 

## Expected behavior

The script should run without rate-limiting errors. 

## Screenshots

![image](https://user-images.githubusercontent.com/39109475/92125999-462e4880-edc5-11ea-9661-fb043e7ae139.png)
****

**Comment by nickytonline** [comment]
You can get a key to avoid this error, but the work in #160 will make this a non-issue.

**Comment by nickytonline** [comment]
This is no longer an issue at all since #228.
