### ISSUE TITLE
Find a Job submenu stays open after click

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#201]
## Describe the bug

Clicking the menu item 'Find a Job' navigates you to the job board page, but the submenu remains open

## To Reproduce

1. Click the 'Find a Job' menu item from any page on protege.dev
2. You're directed to the correct page, but the submenu stays open

## Expected behavior

The submenu will close when landing on the job board page

## Screenshots

![Screen Shot 2020-09-28 at 3 45 33 PM](https://user-images.githubusercontent.com/36208622/94478724-a7b5bd00-01a1-11eb-8144-6bfe38b1a0f9.png)

### Additional context

The submenu opens when the 'find a job' item is hovered or has focus. Clicking it is probably applying focus, so the submenu stays open afterwards.

Look into forcing a blur() event on the 'Find a job' element when its clicked. *this may not be the fix, but its where I'd look first

**Comment by mrsantons** [comment]
I'd love to take this :D

**Comment by drewclem** [comment]
@mrsantons It's all yours! Let me know if you have any questions
