### ISSUE TITLE
Contrast Errors on the home page

### ISSUE THREAD

**Issue by muchirijane** [drewclem/protege#208]
## Describe the bug
There are some contrast issues on the home page.

## To Reproduce
1. Install the [WAVE](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) browser extension either chrome or firefox would be cool.
2. Enter the protege URL https://protege.dev/
3. Go the wave extension and active it by clicking on its icon
4. You will see contrast errors on the detail tab

## Expected behavior

There should be no contrast errors

## Screenshots
![Constarst issue](https://i.ibb.co/Q80s5yH/dev-protege.png)

## Desktop (please complete the following information):
N/A

## Smartphone (please complete the following information):
N/A
### Additional context

No

**Comment by drewclem** [comment]
Thank you for these a11y issues @muchirijane. We appreciate the effort you put into crafting them so succinctly. However, I believe they were resolved in another PR, but hadn't made it to production when you created these.

I'm going to close the recent a11y issues, but please do not hesitate to bring others to our attention!

**Comment by muchirijane** [comment]
@drewclem, Noted 💯.
