### ISSUE TITLE
Contrast Errors on the find a job page

### ISSUE THREAD

**Issue by muchirijane** [drewclem/protege#209]
## Describe the bug
There are some contrast issues on the home page.

## To Reproduce
1. Install the [WAVE](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) browser extension either chrome or firefox would be cool.
2. Enter the protege URL => https://protege.dev/job-board
3. Go the wave extension and active it by clicking on its icon
4. You will see contrast errors on the detail tab

## Expected behavior

There should be no contrast errors

## Screenshots
<img src="https://i.ibb.co/bXxtNHQ/dev-protege-find-job-error.png" alt="dev-protege-find-job-error" border="0">

## Desktop (please complete the following information):
N/A

## Smartphone (please complete the following information):
N/A
### Additional context

No

**Comment by muchirijane** [comment]
I have a suggestion, can we pick another darker color that's not green to solve the contrast issue.

**Comment by drewclem** [comment]
Closed with comment on #208
