### ISSUE TITLE
Contrast errors on the learning resources page

### ISSUE THREAD

**Issue by muchirijane** [drewclem/protege#210]
## Describe the bug
Contrast errors on the #tags below the learning resources cards

## To Reproduce

1. Install the [WAVE](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh) browser extension either chrome or firefox would be cool.
2. Enter the protege URL => https://protege.dev/learning-resources
3. Go the wave extension and active it by clicking on its icon
4. You will see contrast errors on the detail tab

## Expected behavior

There should be no contrast errors

## Screenshots
<img src="https://i.ibb.co/TcTqjqN/dev-protege-resources-errors.png" alt="dev-protege-resources-errors" border="0">

## Desktop (please complete the following information):
N/A

## Smartphone (please complete the following information):
N/A
### Additional context

No

**Comment by drewclem** [comment]
Closed with comment on #208
