### ISSUE TITLE
Set up and integrate firebase emulator for local development

### ISSUE THREAD

**Issue by danieltott** [drewclem/protege#214]
## Goal

To avoid having to give out firebase creds, let's set up and integrate the [Firebase Local Emulator](https://firebase.google.com/docs/emulator-suite). This would allow contributors to run the app locally for development without needing access to the firebase credentials.

## Reason

- Allow contributors to run the project out of the box without needing credentials
- Speed up development by avoiding the extra outside calls
- Allow local development without a network connection
- Increase security by avoiding passing out credentials to outside contributors
- Allow automated testing to run without specific mocks

## Definition of Done

- [ ] App can be run locally (via `npm run start`) without real Firebase credentials
- [ ] Allow some way (via environment variables most likely) to use the real firebase connection when desired
- [ ] Avoid increasing build size by only importing any emulator-specific stuff when in `development`:

```
if (process.env.node_env === 'development') {
// do any emulator-specific things here
}
```

### Possible extra credit?
- [ ] Assuming the emulator will require _some_ environment variables to start, it may be a good idea to either create an example `.env` file and update the readme instructions to copy it, or perhaps create a setup command that does that that a dev would run once? Not sure about the approach here and it may turn out we don't need any env variables to get going with the emulator

**Comment by danieltott** [comment]
OK looks like there is an emulator:
https://firebase.google.com/docs/functions/local-emulator

Here's an article describing how to hook it up to a react app:
- [Firebase Local Development with Firestore, Cloud Functions and React](https://medium.com/@samshapiro/firebase-local-development-with-firestore-cloud-functions-and-react-c29c188bd60e_
- [Firebase + Create React App](https://peterhrynkow.com/firebase/2018/08/01/firebase-with-create-react-app.html)

**Comment by danieltott** [comment]
This might work out for stripe:
https://github.com/adrienverge/localstripe

**Comment by danieltott** [comment]
https://firebase.google.com/docs/emulator-suite

**Comment by clandau** [comment]
I got this one!

**Comment by clandau** [comment]
hey, I am going to unassign myself. I don't think I'm going to get to it. Sorry!

**Comment by sethburtonhall** [comment]
I recently set this up on a side project and I am looking to jump into contributing. Can I take a look into this one?

**Comment by drewclem** [comment]
It's all yours @sethburtonhall !

**Comment by sethburtonhall** [comment]
I have the Auth and Firestore emulators up and running in my local env. Now I'd like to seed the Firestore emulator with dev data from the cloud.

Here is an excellent approach but requires a little bit of admin work within Firebase (logging into Firebase via CLI, exporting data, etc...).

https://medium.com/firebase-developers/how-to-import-production-data-from-cloud-firestore-to-the-local-emulator-e82ae1c6ed8

Thoughts on this approach? Any other approaches to seeding data to Firestore in emulator? @drewclem do you have a mock data set that I could use locally?

**Comment by drewclem** [comment]
The listings (data and number of) doesn't update often. One of the approaches we've considered is a script that generates json at build time.

But that could pose problems if traffic increases, no? Or maybe a firebase function to rebuild the json when it sees a new entry?

**Comment by sethburtonhall** [comment]
One approach could be to use faker.js within a db write function to populate the local firestore. We could trigger this write within a useEffect or even an "Add mock data" button. But we don't want that in production so may not be the best approach. Regardless, it should be simple enough if I had the correct schema.

The above linked to approach creates a bash script that can be run to populate directly from firestore cloud.

**Comment by sethburtonhall** [comment]
I submitted a PR for this. Check it out and let me know your thoughts.

https://github.com/drewclem/protege/pull/226

**Comment by sethburtonhall** [comment]
oops, accidentally unassigned myself, please reassign me. Thanks.

**Comment by sethburtonhall** [comment]
@danieltott @drewclem @clandau 

Want to give this a look? Maybe we can get it merged today?

https://github.com/drewclem/protege/pull/226

**Comment by drewclem** [comment]
@sethburtonhall I'm going to look at it over the weekend. I appreciate your effort in putting this together for us!

**Comment by sethburtonhall** [comment]
closed via https://github.com/drewclem/protege/pull/247
