### ISSUE TITLE
Next Migration: Migrate learning resources page to getStaticProps

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#230]
## Goal

We currently read a JSON file to list all the learning resources on the learning resources page. This is no longer required as we can leverage Next.js' [getStaticProps](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation).

## Reason

Avoids reading a JSON file on each page load and we should be leveraging what Next.js provides out of the box.

### Tips

Look at #229 for inspiration.

## Definition of Done

- [x] The learning resources page generates static props at build time for the list of contributors.

**Comment by sethburtonhall** [comment]
closed via https://github.com/drewclem/protege/pull/231
