### ISSUE TITLE
Job type drop down does not line up with All Jobs title

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#254]
## To Reproduce

1. Go to http://localhost:3000/job-board
2. The All Jobs heading and job type drop down will not be aligned

## Screenshots

![image](https://user-images.githubusercontent.com/833231/111570678-b1e16d00-877b-11eb-833b-41783c6530a6.png)

## Desktop (please complete the following information):

- OS: macOs 11.2.3
- Browser [e.g. chrome, safari] Firefox Developer Edition
- Version 87.0b9

## Smartphone (please complete the following information):

N/A

**Comment by jenkens-dev** [comment]
@drewclem @sethburtonhall  Would love to work on this if it's available!

**Comment by drewclem** [comment]
@jenkens-dev Its all yours!!. For this task, work directly off of main so we can get it to production sooner. Staging is backed up while we work on a big feature, but this one will benefit production UI Immediately

**Comment by nickytonline** [comment]
Just a reminder that once it's in main, we'll also need to get this in the develop branch so the fix is not lost.
