### ISSUE TITLE
Add the jest JavaScript Testing Framework

### ISSUE THREAD

**Issue by nickytonline** [drewclem/protege#255]
## Goal

What will this issue accomplish?

This will allow us to write unit and component tests, where appropriate. 

## Reason

It will potentially improve the stability of the app as well as improve confidence in shipping to production.

### Tips

- Install [jest](https://jestjs.io/)
- Install jest plugins. See the [Forem jest configuration](https://github.com/forem/forem/blob/master/jest.config.js) for inspiration.

## Definition of Done

Jest is configured and runs as part of the CI/CD pipeline.

**Comment by nickytonline** [comment]
You mentioned you had wanted to work on this @andreamartz.

**Comment by andreamartz** [comment]
Yes, I do! Please assign it to me.
