### ISSUE TITLE
Tailwind Just-In-Time Compiler

### ISSUE THREAD

**Issue by sethburtonhall** [drewclem/protege#264]
Explore the new JIT build feature in Tailwind to make sure we have an optimized file size.

* https://github.com/tailwindlabs/tailwindcss-jit
* https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css
* https://dev.to/this-is-angular/why-tailwind-s-just-in-time-mode-is-a-game-changer-and-how-to-use-it-right-now-36c0

**Comment by AlexVCS** [comment]
I'm reading up on it and would like to give this a go!

**Comment by AlexVCS** [comment]
I've added the JIT library to my local version of the project. I think there are more optimizations that can be done, but I'm trying to see how much CSS we're shipping to the browser with or without JIT. That way we have an idea of the benefits we'd be getting. I haven't been able to find a way how to do this yet, does anyone have ideas?

**Comment by AlexVCS** [comment]
@drewclem no prob! I added JIT to the postcss config and that's about it. I can push that and see if you'd like more to be changed :)

**Comment by drewclem** [comment]
@AlexVCS That sounds good. Push it!

**Comment by drewclem** [comment]
Closed with #305
