### ISSUE TITLE
Job board filter slug not updating properly

### ISSUE THREAD

**Issue by javila35** [drewclem/protege#304]
## Describe the bug

While on the job board page, using the drop down menu on the job board component to select a stack does not update the url. 

While on the job board page, using the drop down menu on the navigation component updates the url but does not update the job board component.

The url and component aren't synced up.

## To Reproduce

1. Go to root page
2. Click on "Find A Job" and select "Front End"
3. Use the drop down menu to select "Back End"
4. No change in URL
5. See error

1. Go to root page
2. Click on "Find A Job" and select "Front End"
3. Click on "Find A Job" and select "Back End"
4. See a change in the url, but Job Board doesn't change

## Expected behavior

When selecting a new stack the url updates. When the url changes, the job board is updated with the correct filter.

## Screenshots

![Screen shot of error.](https://user-images.githubusercontent.com/58503695/119392423-95cee000-bc84-11eb-863f-75e99ffdfd1f.png)

## Desktop (please complete the following information):

- OS: iOS
- Browser [e.g. chrome, safari] Chrome 
- Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by drewclem** [comment]
@javila35 Thanks for this issue! Were you wanting to work on it? Or just documenting it?

**Comment by javila35** [comment]
@drewclem I'd like work on it.

**Comment by drewclem** [comment]
It's all yours @javila35!

**Comment by drewclem** [comment]
Closed with #306
