### ISSUE TITLE
Hide semi-transparent background upon screen resizing

### ISSUE THREAD

**Issue by FounderCasey** [drewclem/protege#316]
## Goal

What will this issue accomplish?

This is a minor change proposing to hide the semi-transparent nav background upon the screen size going above the breakpoint.

## Context

How will this improvement affect the application? Give plenty of context.

Currently, if your screen size changes with the mobile-nav open, you're stuck with the semi-transparent background unless you refresh or manually close it by adjusting the window size.

![protege](https://user-images.githubusercontent.com/19507316/123999990-f8a04f00-d987-11eb-8b77-af373c547ae2.gif)

### Notes

Have an idea how this could be accomplished? Leave notes here!

Tailwind provides us with an easy way to manage visibility, simply adding `lg:invisible` to the div will complete this issue.

## Definition of Done

The mobile-nav background hides when the screen changes while `isNavOpen` is true.

**Comment by drewclem** [comment]
@FounderCasey Thank you for this! I can't believe we haven't seen this already, hahaha.
