### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#55]
Hey! We're assuming that if you're here then you're considering contributing to our mission, and that's great!

If you see something you think could be improved on any area of the site we want to hear about it!

Comment your ideas for improvements below and let's have a chat about implementing it!

A company is only as strong as the community it serves and we'd love for you to help us serve it better!

**Comment by DZuz14** [comment]
https://github.com/drewclem/protege/blob/10e4d82bc7508fba71f6d3ea6fedb5b7e238e8c4/src/components/JobTemplate.js#L39

**Comment by DZuz14** [comment]
Does that useEffect call need to run on every re-render? Also, all of those if statements execute regardless of which conditional matches due to no use of else if.

Might even be easier to create a lookup object sort of like you did with the styles for each element, and abstract the logic away into a separate function that can be passed to the forEach.

**Comment by DZuz14** [comment]
Also, quillStyle object can be moved out of the component and put under your import statements etc. No need to recreate it on every rerender

**Comment by drewclem** [comment]
This is great input! I'll put it in an issue.

**Comment by pickleat** [comment]
I’ve been meaning to refactor this. I did so on my portfolio site with the
same problem. For the look ups.

**Comment by laurentcodes** [comment]
I feel more learning resources could be added to the two lists

**Comment by forresthayes** [comment]
Hi, thanks for building this job board! 

Maybe I missed it, but it would be nice to have a link to protege.dev in this repo's About section or readme file.

**Comment by drewclem** [comment]
@laurentcodes You're absolutely correct! As it stands, this list is basically anything @pickleat and I could think of when we launched. We're absolutely open to adding more to both sections. If there's any you have in mind, you can mention them here - or fork the repo and add them through a PR.

@forresthayes That is a definite 10-4, and I can't believe I forgot to put that in originally. Thanks for mentioning!

**Comment by laurentcodes** [comment]
> @laurentcodes You're absolutely correct! As it stands, this list is basically anything @pickleat and I could think of when we launched. We're absolutely open to adding more to both sections. If there's any you have in mind, you can mention them here - or fork the repo and add them through a PR.
> 
> 
> 
> @forresthayes That is a definite 10-4, and I can't believe I forgot to put that in originally. Thanks for mentioning!

Sure, will do that first thing in the morning, cheers.

**Comment by kylemhudson** [comment]
@drewclem just pushed a new branch to my forked repo at https://github.com/kylemhudson/protege/tree/feature/resource-cards

Working on laying out the Learning Resources into cards with images, a title, description, and eventually tags. 

Not doing a PR yet until I get the rest of the cards implemented. Let me know if I'm missing a step or if you want to discuss. Attaching a screenshot here of WIP. 

![Screen Shot 2020-07-23 at 11 53 00 PM](https://user-images.githubusercontent.com/14058890/88359745-cf238000-cd41-11ea-89ec-797cfdc131cd.png)

**Comment by laurentcodes** [comment]
This is nice 👍

**Comment by DZuz14** [comment]
If you guys need any help with backend code, I'd be down to help.

**Comment by drewclem** [comment]
@DZuz14 That will be coming in the near future.

Right now we're using firebase for our backend/dashboard but I'm about to start building our own dashboard, and when we have that up and running, we'll be looking to move to a different setup for a backend/database.
