### ISSUE TITLE
JobCard reads timestamp incorrectly

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#65]
The timestamp in our job card component is displaying one month ahead of what it should be. Any current listings should be from the month of May.

https://github.com/drewclem/protege/blob/master/src/components/JobCard.js

![Screen Shot 2020-05-22 at 10 00 57 AM](https://user-images.githubusercontent.com/36208622/82675664-235f9600-9c13-11ea-8b13-b7fe5c7711b5.png)

**Comment by ottogutierrez** [comment]
Submitted a PR for this one as well ( #68 )
