### ISSUE TITLE
Email sign up doesn't clear after submit

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#66]
The input field for the email sign up should clear itself out after someone clicks the submit button.

https://github.com/drewclem/protege/blob/master/src/components/Footer.js

**Comment by ottogutierrez** [comment]
I can work on this if that's ok

**Comment by drewclem** [comment]
That'd be fantastic. Ping me if you need anything

**Comment by ottogutierrez** [comment]
Thanks! I had a couple of min and I'm ready to submit the pull request. Quick question, should I request to merge to Master or Development branch?

**Comment by drewclem** [comment]
PR to development

**Comment by ottogutierrez** [comment]
Sounds good. PR (#67) submitted!
