### ISSUE TITLE
Refactor useEffect() in JobTemplate.js

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#70]
@DZuZ14 made some good observations on ways this useEffect could be tidied up.

> Does that useEffect call need to run on every re-render? Also, all of those if statements execute regardless of which conditional matches due to no use of else if.
> 
> Might even be easier to create a lookup object sort of like you did with the styles for each element, and abstract the logic away into a separate function that can be passed to the forEach.
>
>Also, quillStyle object can be moved out of the component and put under your import statements etc. No need to recreate it on every rerender

**Comment by pickleat** [comment]
Great stuff! I’ve been meaning to refactor this. I did so on my portfolio site with the same problem. Although I’m not sure why we’d move the quillStyle object out. It isn’t used anywhere else.

**Comment by pickleat** [comment]
@DZuz14 do you want to take this one? I don't want to step on your toes if you were planning on it.

**Comment by pickleat** [comment]
Working on this.
