### ISSUE TITLE
Create contributors page

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#82]
One thing we absolutely want to do is highlight the amazing people contributing their time to helping here. This issue will be to create a contributors page that allows that. When it comes to adding data to the table, just add a few entries of dummy-text and we'll update it once the PR is approved.

There will be a few steps needed to complete this task - there's a design comp at the bottom of this for reference:

- [x] Remove first 'Find a Job' nav item completely, rename 'Quick Filter' to 'Find a Job'
- [x] Add a 'Contributors' nav item between 'Get in Contact' and 'Post a Job'
- [x] Add route for /contributors to App.js and routes.js
- [x] Create Contributors.js file in /pages directory
- [x] Add dummy-content/styling to Contributors.js

Bonus: - [ ] Add cypress test for new contributors page. (reference other page tests in ~/cypress/integration/pages - you're basically just testing to ensure that the page is rendering)

![Screen Shot 2020-06-29 at 10 41 56 PM](https://user-images.githubusercontent.com/36208622/86078019-2001ca80-ba5b-11ea-8bd3-8e13d36a83b8.png)

Don't hesitate to shoot me an email if you have any questions regarding the issue @ drewclementsdesign@gmail.com0

**Comment by ottogutierrez** [comment]
Hi there! I would like to work on this. Is there a specific timeline you need to see this done?

**Comment by drewclem** [comment]
No timeline!

**Comment by ottogutierrez** [comment]
Ok sounds good! I’ll be sending you an email tonight with some questions then 😀

**Comment by drewclem** [comment]
Looking forward to it

**Comment by pickleat** [comment]
Reviewing this now @ottogutierrez!

**Comment by pickleat** [comment]
All the requirements are fulfilled. Thanks @ottogutierrez!
