### ISSUE TITLE
Nav needs active state

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#83]
Our nav currently has a hover state but lacks any indication of which page the user is currently on.

The active state can be the same as the hover state - it just needs to persist when a user is on that given page.

![Screen Shot 2020-06-29 at 10 56 42 PM](https://user-images.githubusercontent.com/36208622/86078298-cea60b00-ba5b-11ea-902f-97ac76e07707.png)

**Comment by ottogutierrez** [comment]
I would love to tackle this one!

**Comment by drewclem** [comment]
@ottogutierrez All yours!

**Comment by ottogutierrez** [comment]
Hi guys, for the mobile version, is the active link required? and would you like the same styling?

**Comment by drewclem** [comment]
Yeah, just give it full opacity

**Comment by ottogutierrez** [comment]
Ok no problem! Thanks!
