### ISSUE TITLE
Disable 'apply' buttons on job listing preview

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#84]
Currently, stage 2 of the _Post a job_ form displays what the job listing will look like for the user's approval. However, the apply buttons are active and if clicked will redirect the user, resulting in them losing any data they'd previously entered.

Stage 2 of the form is being rendered by JobTemplate.js. I think this could be accomplished by checking the route? I.E. If the route is not /job-board/*job-id* then the buttons should be disabled.

Summary: The apply buttons in JobTemplate.js should only be active from the /job-board route

![Screen Shot 2020-06-29 at 11 07 19 PM](https://user-images.githubusercontent.com/36208622/86079042-7ff97080-ba5d-11ea-822a-7c5ca7e99df9.png)

**Comment by forresthayes** [comment]
I’ll take this one!

**Comment by drewclem** [comment]
All yours!
