### ISSUE TITLE
Add placeholder to URL inputs in job form

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#85]
The url inputs 'How to Apply' and 'Company Website' require http:// or https:// to pass validation. However, this isn't apparent from the ui. This is in the PostAJobForm.js file

All we need to do is add a placeholder indicating one or the other is required.

**Comment by saramccombs** [comment]
I’ll happily tackle this one.

**Comment by drewclem** [comment]
Thanks @saramccombs !
