### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by drewclem** [drewclem/protege#86]
As with any project, there's a delay between when a user reaches a page and when the data is rendered. The sections we're primarily interested in for this issue is the homepage's 'Latest Opportunities' and the list on the job board page.

What's needed is a loading spinner that renders while the data is being retrieved.

- [x] Create LoadingSpinner.js component
- [x] create loading hook in each page file
- [x] set loading to true by default
- [x] set loading to false when data is retrieved

**Comment by saramccombs** [comment]
Would love to tackle this one.

**Comment by pickleat** [comment]
Go for it @saramccombs!

**Comment by pickleat** [comment]
Hey @saramccombs just checking in. Everything going ok?

**Comment by saramccombs** [comment]
You must have been reading my mind. I had this issue open to provide an update after my 9am meeting.

Slightly delayed due to a  recent family emergency with my dad (he's ok) and an interview yesterday. Working on it still. :)

**Comment by pickleat** [comment]
No worries at all @saramccombs, glad he is ok! Just wanted to offer support if needed. Let me know if you do! Thanks again!

**Comment by DZuz14** [comment]
Would the new idea of React Placeholder remove the necessity for this? Just wondering.

**Comment by drewclem** [comment]
@DZuz14 Not at all. The job cards will be the one place where we use a spinner and not a placeholder loader.

With the cards, we want a spinner to (hopefully) give the idea that the app is gathering all of the jobs - "we don't know how many or what they are, but we're grabbing them all and dropping them in front of you."

Whereas with the other content, that was created by us, the idea is more of a "we know what and how many there are, hold tight while we get them"

More of a pseudo-UX thing. I apologize if that didn't make any sense - but that's how it plays out in my head.
